version: '3'
services:
  app:
    build: .
    ports: 
      - 8008:8008 
    restart: on-failure
    volumes:
      - app:/usr/src/app/
    depends_on:
      - postgres          
    networks:
      - postgres 
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${databaseName}
      - POSTGRES_PASSWORD=${databasePassword}
      - POSTGRES_DB=${databaseName}
      - DATABASE_HOST=${databaseHost}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

volumes:
  app:
  db:                  

# Networks to be created to facilitate communication between containers
networks:
  postgres:
    driver: bridge